version: '3.7'

services:
  #
  # Blockchain archive node
  #
  substrate-node:
    image: substrate-client:kusama-latest
    hostname: substrate-node
    build: ./substrate-client
    volumes:
      - 'substrate-data:/data'
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: -d /data --rpc-external --ws-external --rpc-cors=all --pruning=archive --name 'Polkastats 🤖 v3'
  #
  # SQL data base
  #
  postgres:
    image: postgres
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - './sql/polkastats.sql:/docker-entrypoint-initdb.d/polkastats.sql'
    environment:
      POSTGRES_USER: 'polkastats'
      POSTGRES_PASSWORD: 'polkastats'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polkastats"]
      interval: 5s
      timeout: 5s
      retries: 5
  #
  # Hasura
  #
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
    - "8082:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://polkastats:polkastats@postgres:5432/polkastats
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  #
  # Block listener crawler
  #
  listener:
    image: polkastats-backend:latest
    build:
      context: ../../
      dockerfile: ./docker/polkastats-backend/backend/Dockerfile
    command: /usr/app/polkastats-backend-v3/crawlers/block-listener.js    
    depends_on:
      - "postgres"
    environment:
      - NODE_ENV=production
  #
  # Block harvester crawler
  #
  harvester:
    image: polkastats-backend:latest
    command: /usr/app/polkastats-backend-v3/crawlers/block-harvester.js
    depends_on:
    - "postgres"
    environment:
      - NODE_ENV=production
#
# Persisten volumes
#
volumes:
  db-data: {}
  substrate-data: {}
