version: '3.4'
services:

  substrate-node:
    image: substrate-client:kusama-latest
    hostname: substrate-node
    build: ./substrate-client
    volumes:
      - 'polkastats-substrate-data:/data'
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: --rpc-external --ws-external --rpc-cors=all --pruning=archive --name '🤖 PolkaStats'

  mysql:
    image: mysql:latest
    hostname: mysql
    volumes:
      - 'polkastats-db-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkastats

volumes:
  polkastats-db-data: {}
  polkastats-substrate-data: {}
